# Generated by Django 5.2.5 on 2025-08-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velo',
            name='date_ajout',
        ),
        migrations.AddField(
            model_name='velo',
            name='batterie',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='velo',
            name='station_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='velos_originaires', to='gestion.station'),
        ),
        migrations.AlterField(
            model_name='velo',
            name='station_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='velos_actuels', to='gestion.station'),
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('BATTERIE', 'Batterie faible'), ('FREIN', 'Problème de freinage'), ('STATION', 'Vélo mal stationné'), ('AUTRE', 'Autre')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('velo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.velo')),
            ],
        ),
    ]
