# Generated by Django 5.2.5 on 2025-08-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_velo_date_ajout_velo_batterie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velo',
            name='station_origine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='velos_originaires', to='gestion.station'),
            preserve_default=False,
        ),
    ]
