# Generated by Django 5.2.5 on 2025-08-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_velo_station_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velo',
            name='station_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='velos_originaires', to='gestion.station'),
        ),
    ]
